name: stylefront
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  permission_handler: ^11.0.0
  image_picker: ^1.1.2
  camera: ^0.11.0
  speech_to_text: ^7.0.0
  html: ^0.15.0
  shared_preferences: ^2.0.18
  provider: ^6.1.2
  path_provider: ^2.0.13
  json_serializable: ^6.6.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  carousel_slider: ^5.0.0
  font_awesome_flutter: ^10.0.0
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  esewa_flutter_sdk:
    path: ./eSewaSdk/esewa_flutter_sdk
  dio: ^5.7.0
  http: ^1.2.2
  khalti_flutter: ^3.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/LOGO_cropped.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fashion_sample_5k.csv
    - assets/icons/LOGO_cropped.png
    - assets/icons/LOGOcolor.png
    - assets/icons/
    - assets/styles/
    - assets/payment/
    - assets/posture/posture.png

dependency_overrides:
  intl: ^0.19.0
